// holds robot names
var robotNames = [];

// Robot constructor, creates robot that has property name
function Robot() {
  this.name = "";
  //sets property name
  this.setName();
}

// creates a random character
function randChar() {
  // returns a random char, generated by random number 65-90 that represents uppercase letter ascii value.
  return String.fromCharCode(Math.random() * 25 + 66);
}

Robot.prototype.setName = function() {
  // gets a 3 digit random number
  var num = Math.floor(Math.random() * 899 + 100);
  // creates robotname by getting 2 random chars by calling randChar() 2 times and concatinating both with num
  this.name = randChar() + randChar() + num;
  // checks if a robot name exists for sake of uniqueness and if it doesn't add it, if it does set the name again
  robotNames.indexOf(this.name) === -1 ? robotNames.push(this.name) : this.setName();
};

// resets name of this robot
Robot.prototype.reset = function() {
  this.setName();
};

module.exports = Robot;